version: "3.2"
services:
  octoprint:
    privileged: true
    build: "."
    image: compscidr/octoprint:${tag}
    ports:
      - 5000:5000
    environment:
       - UDEV=1
    devices:
       - /dev:/dev
